### ISSUE TITLE
Reduce JS build size

### ISSUE THREAD

**Issue by rufuspollock** [datopian/frontend-showcase-js#116]
Current compressed bundle size is around 2.1MB. Would like to get this < 500 Kb if we could.

**Comment by anuveyatsu** [comment]
~~Production build is failing - need to fix that first. So moved to Icebox for now.~~

**Comment by anuveyatsu** [comment]
- Plotly is taking ~600KB and we only importing basic module (full one is 1.9MB)
- Handsontable is taking ~600KB
- Lodash is taking 540KB.

**Comment by rufuspollock** [comment]
@anuveyatsu why are we using all of lodash - i thought babel was smart and only inlined the functions we used ...

Also any way to get handsontable size down? (that's 600Kb compressed right!)

**Comment by anuveyatsu** [comment]
@rufuspollock my previous comment was not accurate. Here is actually what is making our bundle file in descending order:
1. Handsontable - 570KB
2. Plotly - 440KB
3. moment - 177KB
4. D3 - 148KB
5. Vega - 146KB
6. ReactDOM - 106KB
7. Vega-lite - 98KB
8. Lodash - 88KB
...

I'll try to find out a way to decrease the size of Handsontable.

**Comment by subhankarb** [comment]
@anuveyatsu, @rufuspollock  there is a webpack plugin https://github.com/webpack-contrib/compression-webpack-plugin. We can try that.

**Comment by rufuspollock** [comment]
@anuveyatsu agreed re reducing handsontable (that's massive).

Right now we can at least drop vega and vega-lite and add them back when we need them.

Re ReactDOM - is that different from React and if so why do we need it.

Plotly and D3 = 600Kb. Not small ;-) 

**Minification and Compression** I'd assumed we were minifying bundle.js. Are we doing that? Compression is a much bigger deal as it causes overhead and so I'd be hesitant on that.

**Comment by anuveyatsu** [comment]
@rufuspollock dropping all Vega related libraries would decrease bundle size by ~350KB.

ReactDOM was a part of React library until v0.14. Now it's separate but we need it for rendering React components into DOM. It is required. Some more information about that: http://stackoverflow.com/questions/34114350/react-vs-reactdom

Well, will try to figure out smth with Plotly + D3..

Yes, we're already have minified bundle.js. Probably compression is the only way left to significantly reduce bundle size.

**Comment by rufuspollock** [comment]
FIXED. WONTFIX. With caching this is actually not too bad. I think we can leave for now.
