### ISSUE TITLE
Errors in datapackage data validation / casting cause views not to show

### ISSUE THREAD

**Issue by rufuspollock** [datopian/frontend-showcase-js#121]
See https://staging.datapackaged.com/core/co2-ppm

![image](https://cloud.githubusercontent.com/assets/180658/23598724/8c8c95f2-023c-11e7-9d80-9510d8ac720c.png)

## Tasks

* [x] Identify exact cause (I've asked @roll about this on the gitter channel)
* [ ] Either patch upstream in datapackage-js or implement workaround

**Comment by roll** [comment]
@rufuspollock 
@subhankarb 
But this dataset still doesn't have valid date fields:

```
date

datetime; date; time

Tthe field contains temporal values such as dates, times and date-times.

format: (datetime, date and time share the these same options)

default: An ISO8601 format string.
date: This MUST be in ISO8601 format YYYY-MM-DD
datetime: a date-time. This MUST be in ISO 8601 format of YYYY-MM-DDThh:mm:ssZ in UTC time
time: a time without a date
```

But `CO2 PPM` has things like `2005` as date with default format.

**Comment by rufuspollock** [comment]
@roll can we use `yearmonth` type yet with datapackage-js?

**Comment by roll** [comment]
@rufuspollock 
No. It should support prev "stable" state of specs with `fmt:pattern`.

**Comment by rufuspollock** [comment]
@subhankarb here we should just go and fix the upstream data package - fix in github and then reupload to the DPR.

See https://github.com/datasets/co2-ppm/issues/8

**Comment by subhankarb** [comment]
@rufuspollock raised pull request https://github.com/datasets/co2-ppm/pull/9

**Comment by subhankarb** [comment]
FIXED.
Fixed with this pull request : https://github.com/datasets/co2-ppm/pull/9
