### ISSUE TITLE
Misc Resource Table fixes and improvements

### ISSUE THREAD

**Issue by rufuspollock** [datopian/frontend-showcase-js#125]
Various improvements and fixes

 * [x] <del>Can not select data in a box according</del>
 * [ ] Date field is not properly rendered (have time as well as date). Should add a default date format if no date format field in date type column.
 * [x] Column resize is not enabled

**Comment by subhankarb** [comment]
Can not select data in a box: INVALID. As there are only two option editor or readonly. We are using `readonly` mode. So we should stay with this mode.

**Comment by subhankarb** [comment]
@rufuspollock what i should do with date field format ? Should we leave it for now?

**Comment by rufuspollock** [comment]
FIXED. I'm closing for now but we will need to think about how we render the date field at some point later.
