### ISSUE TITLE
Research alternative grid implementations

### ISSUE THREAD

**Issue by rufuspollock** [datopian/frontend-showcase-js#141]
Handsontable is pretty heavy duty.

Other options I've seen others recommend:

https://github.com/bvaughn/react-virtualized

our wants:

* Speed
* Ability to scale to thousands of rows
* Easy copy and paste
* [maybe] Option to extend to editing later on

**Comment by anuveyatsu** [comment]
We have done further research on `react-virtualized` and implemented it - #153 
However, we have reverted the code to use Handsontable again - #155
