### ISSUE TITLE
Handsontable values alignment 

### ISSUE THREAD

**Issue by anuveyatsu** [datopian/frontend-showcase-js#163]
At the moment, values in handsontables are centred that is not our desired thing. We want it to be appropriately aligned so it is more readable and looks good.

## Acceptance criteria

* [ ] numbers are on the right
* [ ] dates and text on the left

## Tasks

**Comment by anuveyatsu** [comment]
DUPLICATE - will be fixed in https://github.com/frictionlessdata/datapackage-render-js/issues/39

**Comment by zelima** [comment]
@anuveyatsu please remove estimate if invalid/duplicate
