### ISSUE TITLE
Vega is not working 

### ISSUE THREAD

**Issue by subhankarb** [datopian/frontend-showcase-js#23]
#### Description
while parsing csv we are getting error:
```
vega.js:10711 [Vega Err] TypeError: (spec || []).forEach is not a function
    at Object.parseData [as data] (vega.js:15253)
    at parse (vega.js:16503)
    at Object.parseSpec [as spec] (vega.js:16465)
    at Object.embed (embed.js:97)
    at Chart.componentDidUpdate (bundle.js:21568)
    at measureLifeCyclePerf (bundle.js:15061)
    at bundle.js:15715
    at CallbackQueue.notifyAll (bundle.js:7694)
    at ReactReconcileTransaction.close (bundle.js:18424)
    at ReactReconcileTransaction.closeAll (bundle.js:8879)
```

#### Step-by-step implementation
* [x] have data loading and CSV parsing outside of vega-lite
* [x] have vega-lite working as a node module
* [x] ~~refactor `index.js` to pass graph type to DataPackageViewContainer~~ Graph type is specified in a descriptor's view attribute.
* [x] refactor DataPackageViewContainer:
  * [x] create a new method for generating Vega-Lite spec
  * [x] refactor `componentWillReceiveProps` method - if statement depending on graph type
  * [x] refactor `render` method - if statement depending on graph type, so we render Plotly or Vega-lite: https://facebook.github.io/react/docs/conditional-rendering.html
* [x] refactor vega-lite component to render multiple charts

#### Acceptance criteria
* [x] Have Vega graph working with:
  * [x] single view - single series
  * [x] ~~single view - multiple series~~ will be fixed in https://github.com/frictionlessdata/dpr-js/issues/69
  * [x] multiple views - each with a single series
  * [x] ~~multiple views - mixed single and multiple series~~ will be fixed in https://github.com/frictionlessdata/dpr-js/issues/69

**Comment by anuveyatsu** [comment]
@subhankarb so as Handsontable and Plotly is working, I believe this is a Vega's built-in parser issue. Maybe I can try to replace it with Papaparse.

**Comment by subhankarb** [comment]
@anuveyatsu 👍

**Comment by rufuspollock** [comment]
@subhankarb @anuveyatsu i would suggest focusing on getting a failing test locally and then fix that and then deploy.

**Comment by subhankarb** [comment]
Did not complete in 2nd Jan milestone. Moving to 16th Jan milestone.

**Comment by anuveyatsu** [comment]
FIXED in https://github.com/frictionlessdata/dpr-js/pull/68

**Comment by rufuspollock** [comment]
@anuveyatsu can you add a brief note about what we need to do here? My impression is that the original CSV parse error stuff was no longer relevant and this was more about refactoring the vega stuff to use the new react / redux stuff.

**Comment by anuveyatsu** [comment]
@rufuspollock I have added step-by-step implementation and acceptance criteria in the very first comment, which is created by @subhankarb. Vega-lite was loaded via CDN when we were getting this error on the site. Now we're using it as a npm package and parsing csv outside of vega-lite.
At the moment, this issue is fixed.
