### ISSUE TITLE
[chart] plotly does not render multiple lines

### ISSUE THREAD

**Issue by anuveyatsu** [datopian/frontend-showcase-js#31]
At the moment Plotly renders a single line chart. But we need to handle cases when there are 2+ line charts, assuming that they share a single X axis (e.g. date).

**Comment by rufuspollock** [comment]
@anuveyatsu before you start work on this can you describe the *precise* issue in more detail. I.e. is this multiple views in one or one view with multiple lines in it?

**Comment by anuveyatsu** [comment]
@rufuspollock this is for one view with multiple lines in it. For example, in datapackage.json:
```javascript=
 "views": [
    {
      "type": "Graph",
      "state": {
        "group": "Date",
        "series": ["Interpolated", "Trend"],
        "graphType": "lines-and-points"
      }
    }
  ]
```
so ```series``` key has a value of Array type when there should be multiple lines in a view.

At the moment, DataPackage class is not expecting Array here, it is expecting String as for a single line.

**Comment by rufuspollock** [comment]
Ok, so this is something we definitely want to support. Let's get a breaking test and then fix.
