### ISSUE TITLE
[table] handsontable does not work with multiple resources

### ISSUE THREAD

**Issue by anuveyatsu** [datopian/frontend-showcase-js#32]
Handsontable should be rendered for each data resource. But at the moment it renders only one table for the first data resource.

*This issue being implemented in https://github.com/frictionlessdata/dpr-js/issues/49*

**Comment by subhankarb** [comment]
Did not complete in 2nd Jan milestone. Moving to 16th Jan milestone.

**Comment by anuveyatsu** [comment]
FIXED in https://github.com/frictionlessdata/dpr-js/pull/63
