### ISSUE TITLE
[tests] implement Jest tests for React components

### ISSUE THREAD

**Issue by anuveyatsu** [datopian/frontend-showcase-js#33]
We need to implement Jest tests for plotly chart and handsontable components to make sure they render on the page.

**Comment by rufuspollock** [comment]
@anuveyatsu if you are working on this now **please** make sure it is assigned to the current milestone (2 Jan).

**Comment by anuveyatsu** [comment]
at the moment, tests are very limited - they only test for the initial state. I need to suspend this issue until I have done state management for components, e.g. using Redux or creating parent component. Otherwise, it is very complicated and not much documentation is available.

**Comment by anuveyatsu** [comment]
FIXED - very basic tests now working.
