### ISSUE TITLE
[dataflow] implement state management - Redux

### ISSUE THREAD

**Issue by anuveyatsu** [datopian/frontend-showcase-js#34]
Without proper state management the app is getting more difficult to maintain, scale and test. At this point, we need to implement well known state management library for React app - Redux, because it is well documented and popular among React community.

* [ ] Research how to do this
* [ ] Split components into components and containers
* [ ] Move logic from components to containers: graph and table specs should be constructed in containers; leave components as presentational components.
* [ ] Create a Redux store
* [ ] Create actions, action types, reducers.
* [ ] Connect Redux with React containers
* [ ] Implement Redux-Thunk for async call

Readings:

* Tutorial on [Redux: good intro](https://teamtreehouse.com/library/building-applications-with-react-and-redux)
* Tutorial on [Async in Redux](https://app.pluralsight.com/library/courses/react-redux-react-router-es6/table-of-contents)
* Blogpost: [React-Redux-Vega](https://medium.com/@pbesh/react-and-vega-an-alternative-visualization-example-cd76e07dc1cd#.m5hgzbuk3)

## Outline of implementation

```
# file / code layout
* src
   * js
        * DataPackage.js
        * HandsontableSpec.js
        * PlotlySpec.js
        * VegaLiteSpec.js
    * components
        * plotlyChart.js
        * vegaliteChart.js
        * table.js
    * containers
        * Chart.js
        * Table.js
    * stores
        * ...
    * actions
    * actiontypes
    * reducers
```

**Comment by anuveyatsu** [comment]
* modulerize components into components and containers
* mainly spend time on learning Redux (on my own time)
* create stores
* create actions

**Comment by rufuspollock** [comment]
DUPLICATE now of #43

**Comment by rufuspollock** [comment]
Moved to 16 Jan milestone as that is the correct one.
