### ISSUE TITLE
datapackage.js - use the library for loading datapackage and resources

### ISSUE THREAD

**Issue by anuveyatsu** [datopian/frontend-showcase-js#42]
What is the datapackage stuff being used for? It is replacing:

* Load of `datapackage.json`
* Load of DataPackage resource data
* Our DataPackage class object (that encapsulates some structure plus looking up resource paths)

Currently we are doing this "by hand" see for e.g.

* datapackage.json loading: https://github.com/frictionlessdata/dpr-js/blob/gh-pages/src/components/plotlyChart.js#L25
* Resource data loading: https://github.com/frictionlessdata/dpr-js/blob/gh-pages/src/components/plotlyChart.js#L39

Steps:

* [x] Write a first test for what we want to do
  * [x] Load `datapackage.json` e.g. test a method that looks like getDataPackage(url) with our fixture data
  * [x] Load resource data
* [x] Look at https://github.com/frictionlessdata/datapackage-js and https://github.com/frictionlessdata/jsontableschema-js
* [x] Get that passing in code
* [x] Get that running in the browser (does it work there?)

```javascript=
Example first failing test

describe('xxx', () => {
  // right now we can use our fixture data or get fancy and mock out the ajax call
  it('should load the datapackage.json and return a promise', () {
    let dp = new DataPackage(dpUrl);
    dp.load().then(function() {
      // test dp has the right data!!
    });
  });
});
```

**Comment by rufuspollock** [comment]
FIXED. We have this working using the datapackage-js library.
