### ISSUE TITLE
Add container components

### ISSUE THREAD

**Issue by anuveyatsu** [datopian/frontend-showcase-js#47]
> At the moment, all operations such as loading datapackage and resources take place inside a single React component. For better management, maintenance and scalability, we could split those components into 2 different parts - container and presentational components. In container components all logic will take place - loading datapackage and resources, converting spec, converting raw data. So in presentational components we only use props passed by container components.

### Steps:
* [x] Create `containers` folder in `./src/`. In this folder create `DataPackageViewContainer.js` and `TabularResourceViewContainer.js`.

### For `DataPackageViewContainer.js`:
* [x] Use some boilerplate code from previous React code and leave only `constructor` and `render` methods.
* [x] Create `generateSpec` method in this class for building Plotly spec.
* [x] Create `convertData` method in this class for converting data into Plotly format.
* [x] Create `componentDidMount` and dispatch redux actions for loading datapackage and resources there.
* [x] Create `componentWillReceiveProps` method - use descriptor and data here to convert them into required format.
* [x] In `render` method pass spec and data to Plotly component.

### For `TabularResourceViewContainer.js`:
* [x] Repeat all steps for `DataPackageViewContainer.js`, **but**:
  * [x] Do not dispatch redux actions here - just use `componentWillReceiveProps` method.
  * [x] Use HandsOnTable instead of Plotly.

**Comment by rufuspollock** [comment]
@anuveyatsu this looks good - i assume it is implicit that you start each step with a test (if that is appropriate for that step).

**Comment by anuveyatsu** [comment]
FIXED https://github.com/frictionlessdata/dpr-js/pull/50
