### ISSUE TITLE
Create publisher details component

### ISSUE THREAD

**Issue by subhankarb** [datopian/frontend-showcase-js#60]
### Description

Publisher details component is the header of the publisher dashboard page. This component will contain data of the data package:

- publisher name
- <del>publisher description</del> - does not exist yet
- title
- <del>contact [if it comes from backend. If the contact is private then it will not there]</del> - does not exist
- joined (created at)

Note: these will be passed as props from container component.

### Step-by-step implementation

* [x] create presentational component `PublisherDetails`
* [x] in render method have `div` element with publisher name in `h1` element and publisher description as paragraph

### Acceptance criteria
* [ ] should render publisher name and description

**Comment by anuveyatsu** [comment]
This component should contain publisher name, title and joined date.

**Comment by anuveyatsu** [comment]
FIXED in https://github.com/frictionlessdata/dpr-js/pull/77
