### ISSUE TITLE
Implement Sign up/Sign in flow

### ISSUE THREAD

**Issue by subhankarb** [datopian/frontend-showcase-js#61]
Right now we have signup/sign in flow in flask generated pages. We have to move the flow to react. 

Tasks:
- [ ] include auth0 library
- [ ] save token in local storage and check that token

Acceptance criterial:
- [ ] User gets logged in 
- [ ] After logged in user redirect to home page.
- [ ] Logged out if token expires

**Comment by rufuspollock** [comment]
I'm removing this from this sprint as not a priority.

**Comment by subhankarb** [comment]
INVALID.
As we are move back from react to MPA. We do not need to create this page.
