### ISSUE TITLE
Display uploaded packages on the dashboard page

### ISSUE THREAD

**Issue by Fak3** [datopian/frontend-showcase-js#62]
The dashboard page should have a list of the packages that user uploaded in the past (in some form).

To be discussed: how it should look like?

* should we divide packages by publishers (if the user is a member or owner of a few)?

### Original user stories

_As a member of multiple publishers, I want to quickly find all my recently uploaded packages, so that I can reinspect a package and fix errors as fast as possible._

**Comment by rufuspollock** [comment]
INVALID. This should be on dpr-api repo (if we need it as an issue for now at all - it is a good idea, but probably a user story first)
