### ISSUE TITLE
Registered user dashboard page

### ISSUE THREAD

**Issue by Fak3** [datopian/frontend-showcase-js#64]
### Original user stories

_As a {Registered User}, representing organization, I want to create new Owner for this organization, so that I can publish packages on behalf of my organization, and invite other members._

_As a Geek Publisher I want to know what do next after signing up so that I can get going quickly._

_As a member of multiple publishers, I want to quickly find all my recently uploaded packages, so that I can reinspect a package and fix errors as fast as possible._

**Comment by rufuspollock** [comment]
INVALID / WONTFIX. This won't be part of dpr-js and the relevant user stories above are a little confused and not high priority.
