### ISSUE TITLE
Multiple series support for Vega-lite charts

### ISSUE THREAD

**Issue by anuveyatsu** [datopian/frontend-showcase-js#69]
#### Description
At the moment, `generateVegaLiteSpec` method takes resource data and descriptor to generate vega-lite spec, but only for a single series. Vega-lite documentation provides solution for rendering multiple series but it assumes raw data to be in a specific form:
```
symbol,date,price
MSFT,Jan 1 2000,39.81
MSFT,Feb 1 2000,36.35
AMZN,Jan 1 2000,64.56
AMZN,Feb 1 2000,68.87
```
but by default we have:
```
date,price,MSFT,AMZN
Jan 1 2000,39.81,64.56
Feb 1 2000,36.35,68.87
```
#### Step-by-step implementation
* [x] Do further research for handling existing data form.
* [x] In vega-lite spec have a root attribute "layers" that contains configurations for each series:
```
{
  "data": {
    "values": 
       [ { "Date": "2014-01-01T18:00:00.000Z",
           "DEMOOpen": 14.32,
           "DEMOHigh": 14.59,
           "DEMOLow": 14,
           "DEMOClose": 14.23 },
         { "Date": "2014-01-02T18:00:00.000Z",
           "DEMOOpen": 14.06,
           "DEMOHigh": 14.22,
           "DEMOLow": 13.57,
           "DEMOClose": 13.76 },
         { "Date": "2014-01-05T18:00:00.000Z",
           "DEMOOpen": 13.41,
           "DEMOHigh": 14,
           "DEMOLow": 13.22,
           "DEMOClose": 13.55 } ]
  },
  "layers": [
    {
      "mark": "line",
      "encoding": {
        "x": {"field": "Date", "type": "temporal"},
        "y": {"field": "DEMOClose", "type": "quantitative"}
      }
    },
    {
      "mark": "line",
      "encoding": {
        "x": {"field": "Date", "type": "temporal"},
        "y": {"field": "DEMOOpen", "type": "quantitative"}
      }
    }
  ]
}
```
#### Acceptance criteria
* [x] should render multiple series in one view

**Comment by anuveyatsu** [comment]
FIXED in https://github.com/frictionlessdata/dpr-js/pull/70

**Comment by rufuspollock** [comment]
@anuveyatsu personally i don't think this is a top priority in this milestone. I'd also like a bit more info about a situation in which this not work.
