### ISSUE TITLE
Fix failing test for vega and handsontable

### ISSUE THREAD

**Issue by subhankarb** [datopian/frontend-showcase-js#72]
Right now the tests for vega and handsontable is failing. The reason behind that is ja-dom create a separate virtual DOM and vega and handsontable generate DOM in seperate way. So we can not assert that dom is created from this library. So we can only do functional test checking the specs.

**Comment by anuveyatsu** [comment]
FIXED in https://github.com/frictionlessdata/dpr-js/pull/73
