### ISSUE TITLE
Implement Search box for publisher package list

### ISSUE THREAD

**Issue by subhankarb** [datopian/frontend-showcase-js#80]
Background:
Right now we are showing all data packages published by the publisher. Enable user to search among the package lists would be great. 
Current State:
<img width="1285" alt="screen shot 2017-01-26 at 7 07 07 am" src="https://cloud.githubusercontent.com/assets/2178361/22316874/17b74af2-e396-11e6-9199-5fbc2805ee0b.png">
 
In the place of ```Publisher Package List``` there will be a search box which will filter the data packages of the publisher.

Implementation:
Right now the data is present in redux store as ```publisherPage.data[]```
TODO ... How to implement @anuveyatsu plz share your thoughts.

**Comment by anuveyatsu** [comment]
@subhankarb 
1) need to create search box element in `Publisher Package List` component 
2) it should have `onchange` event and that event should fire some filter function that will update state and rerender component

**Comment by rufuspollock** [comment]
@anuveyatsu as per chat with @subhankarb this is not for this sprint as not high priority.

**Comment by rufuspollock** [comment]
FIXED. This was implemented as part of the backend work on publisher and search page. https://github.com/frictionlessdata/dpr-api/pull/228/files#diff-4100543dfd254bcf7fa3f0b347b8a715
