### ISSUE TITLE
Fix page Footer

### ISSUE THREAD

**Issue by subhankarb** [datopian/frontend-showcase-js#81]
Background:
Right now the footer is blocking the scrolling dow of the page

Current state:
<img width="1401" alt="screen shot 2017-01-26 at 7 17 37 am" src="https://cloud.githubusercontent.com/assets/2178361/22317095/8e1c1032-e397-11e6-88b3-8d22d2b281dc.png">

So we can not scroll down any more.

Fix:
We have to fix the css of the footer. Either make it fix to bottom or make full page viewable.

**Comment by anuveyatsu** [comment]
FIXED in https://github.com/frictionlessdata/dpr-js/pull/94
