### ISSUE TITLE
Tests for data package action is not working

### ISSUE THREAD

**Issue by subhankarb** [datopian/frontend-showcase-js#90]
Tests in data package action is not working. We use axios for api call and nock for mocking. But nock is not intercepting the http call. 
Related issues :
- https://github.com/mzabriskie/axios/issues/305
- https://github.com/node-nock/nock/issues/699

**Comment by rufuspollock** [comment]
INVALID / WONTFIX. We don't need this now since we removed all redux stuff as part of #109.
