### ISSUE TITLE
Improve design of the site

### ISSUE THREAD

**Issue by anuveyatsu** [datopian/frontend-showcase-js#96]
### Desription
The site's pages do not have appropriate layout and styling at the moment. It should be intuitive, easily readable, simple, clean and responsive. To do so we use Bootstrap, in particular React-Bootstrap.

### Step-by-step implementation
* [x] Create mock layout for Publisher page
* [x] Convert to React-Bootstrap components, test and push code
* [x] Create mock for Home page
* [x] Convert to React-Bootstrap components, test and push code
* [ ] Create mock layout for Data package view page

**Comment by anuveyatsu** [comment]
Mock layout for Publisher page:
http://codepen.io/anuveyatsu/full/LxOJyw/

**Comment by anuveyatsu** [comment]
Need to reimplement Publisher page with Bootstrap v4

**Comment by rufuspollock** [comment]
@anuveyatsu really like codepen stuff - only sugestion would be to have one item at a time horizontally and list downwards for packages (like repos on github).

**Comment by anuveyatsu** [comment]
@rufuspollock OK, just realised it would be also easier in implementation

**Comment by rufuspollock** [comment]
And probably better on mobile (though i imagine the 4x4 was responsive already ...)

**Comment by anuveyatsu** [comment]
Changed publisher page - one item horizontally http://codepen.io/anuveyatsu/full/LxOveP/

**Comment by anuveyatsu** [comment]
Simple home page - http://codepen.io/anuveyatsu/full/LxeNgy/

**Comment by rufuspollock** [comment]
FIXED. Basically done and we reused this in the main site when we went back to MPA. The data package view page can be separate work.
