### ISSUE TITLE
[blocker] datapackage-test schemas over http

### ISSUE THREAD

**Issue by subhankarb** [datopian/frontend-showcase-js#99]
When we called 
```new Datapackage(descriptor, 'base', false, false, basePath)```

This called ```http://schemas.datapackages.org/registry.json'```  URL.
 
We get the problem in AWS as all url must be through HTTPS. So we gets this error

```Mixed Content: The page at 'https://staging.datapackaged.com/core/finance-vix' was loaded over HTTPS, but requested an insecure resource 'http://schemas.datapackages.org/registry.json'. This request has been blocked; the content must be served over HTTPS.```

We created an issue in ```datapackage-js``` repo https://github.com/frictionlessdata/datapackage-js/issues/54

**Comment by rufuspollock** [comment]
FIXED. This is now fixed thanks to changes upstream - https://github.com/frictionlessdata/datapackage-js/issues/54 is fixed now.
